<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-E194MDNK" failures="6" tests="8" name="Test" time="86.176" errors="0" timestamp="2024-05-26T11:21:45 IST">
  <testcase classname="test.TC001_LoginTest" name="LoginTest" time="3.203"/>
  <testcase classname="test.TC001_LoginTest" name="LoginTest" time="3.167">
    <failure type="java.lang.AssertionError" message="expected [Wrong password.] but found [User does not exist.]">
      <![CDATA[java.lang.AssertionError: expected [Wrong password.] but found [User does not exist.]
at test.TC001_LoginTest.LoginTest(TC001_LoginTest.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="test.TC001_LoginTest" name="LoginTest" time="3.238">
    <failure type="org.openqa.selenium.NoAlertPresentException" message="no such alert
  (Session info: MicrosoftEdge=125.0.2535.51)
Build info: version: &amp;apos;4.20.0&amp;apos;, revision: &amp;apos;866c76ca80&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.10&amp;apos;
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [aaedd7f6fe3011741f95b92602fabd20, getAlertText {}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 125.0.2535.51, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:49332}, msedge: {msedgedriverVersion: 125.0.2535.67 (626a82df5fa7..., userDataDir: C:\Users\boopa\AppData\Loca...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:49332/devtoo..., se:cdpVersion: 125.0.2535.51, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: aaedd7f6fe3011741f95b92602fabd20">
      <![CDATA[org.openqa.selenium.NoAlertPresentException: no such alert
  (Session info: MicrosoftEdge=125.0.2535.51)
Build info: version: '4.20.0', revision: '866c76ca80'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [aaedd7f6fe3011741f95b92602fabd20, getAlertText {}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 125.0.2535.51, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:49332}, msedge: {msedgedriverVersion: 125.0.2535.67 (626a82df5fa7..., userDataDir: C:\Users\boopa\AppData\Loca...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:49332/devtoo..., se:cdpVersion: 125.0.2535.51, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: aaedd7f6fe3011741f95b92602fabd20
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:591)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.alert(RemoteWebDriver.java:1163)
at test.TC001_LoginTest.LoginTest(TC001_LoginTest.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="test.TC001_LoginTest" name="LoginTest" time="3.325">
    <failure type="java.lang.AssertionError" message="expected [Invalid user name and password] but found [Wrong password.]">
      <![CDATA[java.lang.AssertionError: expected [Invalid user name and password] but found [Wrong password.]
at test.TC001_LoginTest.LoginTest(TC001_LoginTest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="test.TC002_SignUpTest" name="SignUpTest" time="3.088">
    <failure type="java.lang.AssertionError" message="expected [Sign up successful.] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: expected [Sign up successful.] but found [This user already exist.]
at test.TC002_SignUpTest.SignUpTest(TC002_SignUpTest.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- SignUpTest -->
  <testcase classname="test.TC002_SignUpTest" name="SignUpTest" time="3.177"/>
  <testcase classname="test.TC002_SignUpTest" name="SignUpTest" time="3.104">
    <failure type="java.lang.AssertionError" message="expected [Invalid user name. Please enter a valid username] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: expected [Invalid user name. Please enter a valid username] but found [This user already exist.]
at test.TC002_SignUpTest.SignUpTest(TC002_SignUpTest.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- SignUpTest -->
  <testcase classname="test.TC002_SignUpTest" name="SignUpTest" time="3.011">
    <failure type="java.lang.AssertionError" message="expected [Invalid password. Please enter a valid password] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: expected [Invalid password. Please enter a valid password] but found [This user already exist.]
at test.TC002_SignUpTest.SignUpTest(TC002_SignUpTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- SignUpTest -->
</testsuite> <!-- Test -->
